name: weather_app
description: "A simple weather app using the Open-Meteo API."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  geolocator: ^13.0.4
  provider: ^6.1.4 
  shared_preferences: ^2.5.3 
  intl: ^0.20.2 
  flutter_svg: ^2.0.17 
  geocoding: ^3.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

